### ISSUE TITLE
Portfolio boxes changing size

### ISSUE THREAD

**Issue by Serneum** [i4web/sern-programming#5]
[Reference](http://sernprogramming.com/portfolio/)

I thought we had added some safeguards to try and keep all of the boxes roughly the same size. This doesn't appear to be the case as some of the project boxes are taller than others, which breaks the rendering of the rows

**Comment by Serneum** [comment]
Link was in the original post. but here's a screenshot
![Imgur](http://i.imgur.com/LcsyIpB.png)

**Comment by i4web** [comment]
@Serneum Can you give me quick access to your admin? I want to take a look at that project post excerpt to see if I can manipulate what shows on the front end through the post edit page.

A fix to this type of issue could be to make that area scrollable but that's generally ugly for the UX but it's a simple fix to the css like this:

```
.sern-project-desc-wrap {
    height: 70px;
    overflow: scroll;
}
```

**Comment by Serneum** [comment]
Access should already be available
![Imgur](http://i.imgur.com/3nDl9t8.png)

I know the original solution was to limit the amount of text visible, as mentioned in your earlier comment. Not sure why it seems to work on some projects but not others

**Comment by i4web** [comment]
@Serneum We're limiting it to 15 words here:

https://github.com/i4web/sern-programming/blob/master/lib/custom.php#L74

The problem with this one will be that from the screenshot there's only really one or two words. If you were to add some spaces or custom enter in an excerpt via the excerpt metabox in the portfolio edit page you'll be able to manipulate it. Unfortunately we're limited with WordPress to only alter the number of words without doing unnecessary string replacements and hacks on the excerpt string.

**Comment by Serneum** [comment]
Can we not just use CSS `text-overflow: ellipsis`?

**Comment by i4web** [comment]
I guess you could. If you use that then code has to be added to remove the built in ellipsis from WordPress or else you'll have "... ..." at the end. If you think you'll have many projects with long strings with no spaces to begin the project content then it's probably worth the give and take on that. I honestly prefer to use the custom excerpt box so you can control what's shown on the front end without having to 

If not, I'll push an update to increase the min-height from 70px to 100px to give you enough buffer. I'm noticing you have another one that's slightly exceeding it so I may just do that increase anyway.

**Comment by Serneum** [comment]
I'll look into using the custom excerpt box. I do think an increase in min-height may be a good idea overall as well.

**Comment by i4web** [comment]
@Serneum Ok cool. I'm going to push an update to the master in a few minutes for that.

**Comment by i4web** [comment]
@Serneum I pushed the update. Let me know how it works once you bring in the changes.

**Comment by Serneum** [comment]
Looks like it's working for me. Thanks.

**Comment by i4web** [comment]
Perfect. Thanks!
